/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CloudinaryVideo {
        "account": string;
        "alias": string;
        "height": string;
        "width": string;
    }
    interface MvVideo {
        "account": string;
        "alias": string;
        "height": string;
        "width": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCloudinaryVideoElement extends Components.CloudinaryVideo, HTMLStencilElement {
    }
    var HTMLCloudinaryVideoElement: {
        prototype: HTMLCloudinaryVideoElement;
        new (): HTMLCloudinaryVideoElement;
    };
    interface HTMLMvVideoElement extends Components.MvVideo, HTMLStencilElement {
    }
    var HTMLMvVideoElement: {
        prototype: HTMLMvVideoElement;
        new (): HTMLMvVideoElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cloudinary-video": HTMLCloudinaryVideoElement;
        "mv-video": HTMLMvVideoElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CloudinaryVideo {
        "account"?: string;
        "alias"?: string;
        "height"?: string;
        "width"?: string;
    }
    interface MvVideo {
        "account"?: string;
        "alias"?: string;
        "height"?: string;
        "width"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "cloudinary-video": CloudinaryVideo;
        "mv-video": MvVideo;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cloudinary-video": LocalJSX.CloudinaryVideo & JSXBase.HTMLAttributes<HTMLCloudinaryVideoElement>;
            "mv-video": LocalJSX.MvVideo & JSXBase.HTMLAttributes<HTMLMvVideoElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
